apiVersion: 1

datasources:
  - name: k6 InfluxDB
    uid: k6-influxdb
    type: influxdb
    access: proxy
    isDefault: true
    url: http://influxdb:8086
    database: k6
    jsonData:
      httpMode: GET
